alter sequence serials_id_seq restart;

insert into serials (title, year_of_premiere, description, created_at, updated_at) values
  ('Game of Thrones', 2011, 'George R.R. Martin''s best-selling book series "A Song of Ice and Fire" is brought to the screen as HBO sinks its considerable storytelling teeth into the medieval fantasy epic. It''s the depiction of two powerful families -- kings and queens, knights and renegades, liars and honest men -- playing a deadly game for control of the Seven Kingdoms of Westeros, and to sit atop the Iron Throne. Martin is credited as a co-executive producer and one of the writers for the series, whose shooting locations include Northern Ireland, Malta, Croatia and Spain.', current_timestamp, current_timestamp),
  ('True Detective', 2014, 'Season 3 of "True Detective" plays out in three separate time periods, telling the story of the 1980 disappearance of a young Arkansas boy and his sister, and a mystery that deepens over decades. Oscar winner Mahershala Ali stars as state police detective Wayne Hays, who recalls the days and weeks immediately following the crime, as well as developments in 1990, when he and his former partner, Roland West, were subpoenaed after a major break in the case. What started as a routine investigation becomes a long journey to dissect and make sense of the crime.', current_timestamp, current_timestamp),
  ('The Walking Dead', 2010, 'Based on the comic book series written by Robert Kirkman, this gritty drama portrays life in the months and years that follow a zombie apocalypse. Led by former police officer Rick Grimes, his family and a group of other survivors find themselves constantly on the move in search of a safe and secure home. But the pressure each day to stay alive sends many in the group to the deepest depths of human cruelty, and they soon discover that the overwhelming fear of the survivors can be more deadly than the zombies walking among them.', current_timestamp, current_timestamp),
  ('The Big Bang Theory', 2007, 'Mensa-fied best friends and roommates Leonard and Sheldon, physicists who work at the California Institute of Technology, may be able to tell everybody more than they want to know about quantum physics, but getting through most basic social situations, especially ones involving women, totally baffles them. How lucky, then, that babe-alicious waitress/aspiring actress Penny moves in next door. Frequently seen hanging out with Leonard and Sheldon are friends and fellow Caltech scientists Wolowitz and Koothrappali. Will worlds collide? Does Einstein theorize in the woods?', current_timestamp, current_timestamp),
  ('Supernatural', 2005, 'This haunting series follows the thrilling yet terrifying journeys of Sam and Dean Winchester, two brothers who face an increasingly sinister landscape as they hunt monsters. After losing their mother to a supernatural force, the brothers were raised by their father as soldiers who track mysterious and demonic creatures. Violent memories and relationship-threatening secrets add additional burdens on Sam and Dean as they investigate all things that go bump in the night. As old tricks and tools are rendered useless and friends betray them, the brothers must rely on each other as they encounter new enemies.', current_timestamp, current_timestamp),
  ('House of Cards', 2014, 'U.S. Rep. Francis Underwood of South Carolina starts out as a ruthless politician seeking revenge in this Netflix original production. Promised the post of Secretary of State in exchange for his support, his efforts help to ensure the election of Garrett Walker to the presidency. But Walker changes his mind before the inauguration, telling Underwood he''s too valuable in Congress. Outwardly, Underwood accepts his marching orders, but secretly he and his wife Claire, an environmental activist, make a pact to destroy Walker and his allies. As the series progresses, Underwood ascends through the ranks of the government -- until his death, at which point Claire gains power. Based on the U.K. miniseries of the same name, the U.S. version offers a look behind the scenes at the greed and corruption in American politics. A number of real-life media figures make cameo appearances.', current_timestamp, current_timestamp),
  ('American Horror Story', 2011, '"American Horror Story" was created by the co-creators of "Glee," but the shows have little in common besides that. The show revolves around the Harmons, a family of three, who move from Boston to Los Angeles in order to reconcile past anguish. What the Harmons don''t know is that the house they''ve moved into is haunted. But it''s not haunted by Casperesque friendly ghosts -- it''s haunted by demonic creatures. The creatures have a history of not only spooking the house''s residents but also devouring them. After living in this house, family patriarch and psychiatrist, Ben, may need a shrink of his own.', current_timestamp, current_timestamp),
  ('Rick and Morty', 2013, 'After having been missing for nearly 20 years, Rick Sanchez suddenly arrives at daughter Beth''s doorstep to move in with her and her family. Although Beth welcomes Rick into her home, her husband, Jerry, isn''t as happy about the family reunion. Jerry is concerned about Rick, a sociopathic scientist, using the garage as his personal laboratory. In the lab, Rick works on a number of sci-fi gadgets, some of which could be considered dangerous. But that''s not all Rick does that concerns Jerry. He also goes on adventures across the universe that often involve his grandchildren, Morty and Summer.', current_timestamp, current_timestamp);
